Drush Rush: Command Helpers
Command Helpers
Helper Functions
Functions to help with Drush Rush Commands.
Functions
_rush_docs_selection ()
Help function to select which docs to display information about.
_rush_show ($params, $mode, $operations)
Helper function to print the params associated with the defined show mode.
rush_invoke ($alias, $command, $args, $options, $function, $type= 'message')
A wrapper for drush_invoke_process().
rush_self_path ()
Helper function to return the path to the Drush Rush module directory.
rush_shell_exec ($cmd, $msg, $error, $function, $type= 'message')
A wrapper for drush_shell_exec() .
Detailed Description
Functions to help with Drush Rush Commands.
Function Documentation
_rush_docs_selection ()
Help function to select which docs to display information about.
Returns
mixed FALSE on error. Array on drush_invoke_process success.
Definition at line 215 of file rush.inc.
{
   $topics = array(
     'rush-ops-tables',
     'docs-rush-ops-db',
     'docs-rush-ops-repo',
     'docs-rush-ops-site',
     'docs-rush-ops-utility',
     'docs-rush-ops-filesystem',
     'docs-rush-ops-host',
   );
   $topics = drush_map_assoc($topics);
   // Present a list of topics as options to the user.
   $topic = drush_choice($topics, 'Enter a number to choose which topic to read.', '!key');
   if ($topic !== FALSE) {
     $args = array($topics[$topic]);
     return drush_invoke_process('@self', 'topic', $args);
   }
   return FALSE;
 }
_rush_show ($params, $mode, $operations)
Helper function to print the params associated with the defined show mode.
Parameters
array $params Required. An associative array of all rush parameters.
string $mode Required. A string containing the name of the mode to show.
array $operations An associative array of all rush operations.
Returns
bool TRUE on success, FALSE on fail via drush_set_error.
Definition at line 139 of file rush.inc.
References rush_message_wrapper().
Referenced by drush_rush(), and drush_rush_show().
{
   switch ($mode) {
     case 'params':
       unset($params['derived_params']);
       unset($params['job']);
       ksort($params);
       $msg = rush_message_wrapper(dt(" PARAMS "), 0);
       drush_print_r($msg);
       drush_print_r($params);
       $msg = rush_message_wrapper(dt(" END PARAMS "), 0);
       drush_print_r($msg);
       return TRUE;
     case 'ops':
       $msg = rush_message_wrapper(dt(" OPERATIONS "), 0);
       drush_print_r($msg);
       drush_print_r($operations);
       $msg = rush_message_wrapper(dt(" END OPERATIONS "), 0);
       drush_print_r($msg);
       return TRUE;
     case 'help':
     case 'h':
       $msg = rush_message_wrapper(dt(" HELP "), 0);
       drush_print_r($msg);
       drush_print_r($params['job']['description']);
       // Create a line space.
       drush_print('');
       drush_print_r($params['job']['help']);
       $msg = rush_message_wrapper(dt(" END HELP "), 0);
       drush_print_r($msg);
       return TRUE;
     case 'derived':
       drush_print_r($params['derived_params']);
       return TRUE;
     case 'paths':
       $msg = rush_message_wrapper(dt(" PATHS "), 0);
       drush_print_r($msg);
       $paths['build_paths']['root_directory_path'] = $params['build']['root_directory_path'];
       $paths['build_paths']['directory_path'] = $params['build']['directory_path'];
       $paths['build_paths']['docroot_path'] = $params['build']['docroot_path'];
       $paths['db_paths']['directory_path'] = $params['db']['directory_path'];
       $paths['global_paths'] = $params['global_locations'];
       drush_print_r($paths);
       $msg = rush_message_wrapper(dt(" END PATHS "), 0);
       drush_print_r($msg);
       return TRUE;
     default:
       if (!empty($params[$mode])) {
         ksort($params[$mode]);
         drush_print_r($params[$mode]);
         return TRUE;
       }
       $msg = dt('[ERROR]: *** The --show option "!option" is not a valid value. Check the spelling of the value. ***', array('!option' => $mode));
       return drush_set_error('DRUSH_RUSH_INVALID_OPTION', $msg);
   }
 }
rush_invoke ($alias, $command, $args, $options, $function, $type = 'message')
A wrapper for drush_invoke_process().
See: http://api.drush.org/api/
Parameters
array $alias The site record to execute the command on. Use '' to run on the current site.
string $command The command to invoke.
array $args The arguments to pass to the command.
array $options The options (e.g. –select) to provide to the command.
string $function The name of the function which called, rush_invoke().
string $type The type of Drush log message to use.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 56 of file rush.inc.
Referenced by rush_op_make(), rush_op_set_drupal_variables(), rush_op_si(), rush_op_sql_create(), rush_op_sql_dump(), rush_op_sql_query(), and rush_op_sql_query_file().
{
   $cmd_string = $command . ' ' . implode(' ', $args) . ' ' . implode(' ', $options);
   if (drush_invoke_process($alias, $command, $args, $options, TRUE)) {
     $msg = dt('[RUN DRUSH]: !cmd_string', array('!cmd_string' => $cmd_string));
     drush_log($msg, $type);
     return TRUE;
   }
   else {
     $msg = dt('[ERROR]: *** !operation failed to run: !cmd_string ***', array(
       '!cmd_string' => $cmd_string,
       '!operation' => $function,
     ));
     return drush_set_error('RUSH_INVOKE_ERROR', $msg);
   }
 }
rush_self_path ()
Helper function to return the path to the Drush Rush module directory.
Returns
string A string containing the path to the Rush module directory.
Definition at line 121 of file rush.inc.
Referenced by _rush_print_ops_table(), rush_drush_command(), and rush_get_global_locations().
{
   return realpath(dirname(__FILE__)) . '/';
 }
rush_shell_exec ($cmd, $msg, $error, $function, $type = 'message')
A wrapper for drush_shell_exec() .
See: http://api.drush.org/api/
Parameters
string $cmd Required. The command to execute. May include placeholders.
string $msg Required. String containing the message to log upon success.
string $error Required. The type of error to log on fail.
string $function The name of the function which called, rush_shell_exec().
string $type The type of Drush log message to use.
Returns
bool TRUE on success, FALSE on failure via drush_set_error().
Definition at line 97 of file rush.inc.
Referenced by rush_op_create_dns(), rush_op_create_vhost(), rush_op_delete_dns(), rush_op_delete_vhost(), rush_op_flow_init(), rush_op_git_add(), rush_op_git_branch(), rush_op_git_checkout(), rush_op_git_clone(), rush_op_git_commit(), rush_op_git_create_branch(), rush_op_git_init(), rush_op_git_pull(), rush_op_git_push(), and rush_op_git_remote_add().
{
   if (drush_shell_exec($cmd)) {
     drush_log($msg, $type);
     return TRUE;
   }
   else {
     $error_msg = dt('[ERROR]: *** Failed to run: !cmd in !function ***', array(
       '!cmd' => $cmd,
       '!function' => $function,
     ));
     return drush_set_error($error, $error_msg);
   }
 }