Drush Rush: Drush Command Callbacks
Drush Command Callbacks
Bootstrap
Callback functions for each Drush Rush command.
Functions
drush_rush ()
Drush rush command callback.
drush_rush_list ()
Drush rush-list command callback.
drush_rush_show ()
Drush rush-show command callback.
Detailed Description
Callback functions for each Drush Rush command.
Function Documentation
drush_rush ()
Drush rush command callback.
Run a rush file with commands in it.
See Also
drush_invoke()
drush.api.php
Backlog:
This does not seem to stop on all operation errors.
Refactor switch case statements.
Returns
bool FALSE on failure.
Definition at line 291 of file rush.drush.inc.
References _rush_list_jobs(), _rush_show(), rush_command_exec(), rush_function_exec(), rush_get_global_locations(), rush_get_operations(), rush_get_params(), rush_job_exec(), and rush_message_exec().
                       {
   $args = drush_get_arguments();
   // Check for the job argument.
   if (!isset($args[1])) {
     $global_locations = rush_get_global_locations();
     // Set default values.
     $directory_path = $global_locations['RUSH_JOBS_DIRECTORY_PATH'];
     $directory_name = $global_locations['RUSH_JOBS_DIRECTORY_NAME'];
     $rush_dir_name = $global_locations['RUSH_HOME_DIRECTORY_NAME'];
     if (drush_get_option('select', FALSE)) {
       $select = drush_get_option('select');
       switch ($select) {
         case 'job-templates':
         case 'jt':
           $directory_path = $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_PATH'];
           $directory_name = $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_NAME'];
           $rush_dir_name = trim($global_locations['RUSH_MODULE_DIRECTORY_PATH'], '/');
           break;
       }
     }
     // Get the jobs list.
     $jobs = _rush_list_jobs($directory_path, $directory_name, $rush_dir_name);
     $jobs = drush_map_assoc($jobs);
     // Present a list of jobs as options to the user.
     $job = drush_choice($jobs, 'Enter a number to choose which job to run.', '!key');
     if ($job !== FALSE) {
       $args[1] = $jobs[$job];
       drush_set_arguments($args);
     }
     else {
       $msg = dt('[Rush]: !message', array('!message' => 'Canceled'));
       drush_log($msg, 'status');
       return;
     }
   }
   $params = rush_get_params();
   $rush_operations = rush_get_operations($params);
   if (drush_get_option('create-branch', FALSE)) {
     $rush_operations[]['f'] = 'git_create_branch';
   }
   if (drush_get_option('show', FALSE)) {
     $show_mode = drush_get_option('show');
     return _rush_show($params, $show_mode, $rush_operations);
   }
   $msg = dt('[ERROR]: An error occurred while running this drush operation: ');
   // @backlog Make a progress meter based on number of operations to run.
   // @backlog Have a finished message.
   foreach ($rush_operations as $op_array) {
     foreach ($op_array as $op_type => $op) {
       switch ($op_type) {
         // The op_type is a function.
         case 'f':
           if (rush_function_exec($op, $params) === FALSE) {
             return drush_set_error('DRUSH_RUSH_OP_ERROR', $msg . $op);
           }
           break;
         // The op_type is a command.
         case 'c':
           if (rush_command_exec($op, $params) === FALSE) {
             return drush_set_error('DRUSH_RUSH_OP_ERROR', $msg . $op);
           }
           break;
         // The op_type is a job to run.
         case 'j':
           if (rush_job_exec($op, $params) === FALSE) {
             return drush_set_error('DRUSH_RUSH_OP_ERROR', $msg . $op);
           }
           break;
         // The op_type is a message.
         case 'm':
           if (rush_message_exec($op, $params) === FALSE) {
             return drush_set_error('DRUSH_RUSH_OP_ERROR', $msg . $op);
           }
           break;
       }
     }
   }
 }
drush_rush_list ()
Drush rush-list command callback.
List all the jobs in the Rush Application folder jobs directory.
See Also
drush_invoke()
drush.api.php
Returns
bool TRUE on success, FALSE on failure.
Definition at line 391 of file rush.drush.inc.
References _rush_list_jobs(), rush_get_global_locations(), and rush_message_wrapper().
{
   $global_locations = rush_get_global_locations();
   // Set default values.
   $msg = rush_message_wrapper(dt('JOBS LIST'), 0);
   $directory_path = $global_locations['RUSH_JOBS_DIRECTORY_PATH'];
   $directory_name = $global_locations['RUSH_JOBS_DIRECTORY_NAME'];
   $rush_dir_name = $global_locations['RUSH_HOME_DIRECTORY_NAME'];
   // If the show option is set to jt then list jobs in the job_templates
   // directory.
   if (drush_get_option('show', FALSE)) {
     $show_mode = drush_get_option('show');
     switch ($show_mode) {
       case 'job-templates':
       case 'jt':
         $msg = rush_message_wrapper(dt('JOB TEMPLATES LIST'), 0);
         $directory_path = $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_PATH'];
         $directory_name = $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_NAME'];
         $rush_dir_name = trim($global_locations['RUSH_MODULE_DIRECTORY_PATH'], '/');
         break;
       case 'locations':
       case 'l':
         $msg = rush_message_wrapper(dt('GLOBAL LOCATIONS'), 0);
         drush_print($msg);
         ksort($global_locations);
         drush_print_r($global_locations);
         return TRUE;
       default:
         $msg = dt('[ERROR]: *** The --show option "!option" is not a valid value. Check the spelling of the value. ***', array('!option' => $show_mode));
         return drush_set_error('DRUSH_RUSH_INVALID_OPTION', $msg);
     }
   }
   // Tell the user what list they will get.
   drush_print($msg);
   // Get the jobs list.
   $jobs = _rush_list_jobs($directory_path, $directory_name, $rush_dir_name);
   foreach ($jobs as $job) {
     drush_print($job);
   }
   $msg = rush_message_wrapper(dt('END LIST'), 0);
   drush_print($msg);
   return TRUE;
 }
drush_rush_show ()
Drush rush-show command callback.
A utility to inspect operations or params without actually running a job.
See Also
drush_invoke()
drush.api.php
Definition at line 450 of file rush.drush.inc.
References _rush_show(), rush_get_operations(), and rush_get_params().
{
   $params = rush_get_params();
   $rush_operations = rush_get_operations($params);
   $args = drush_get_arguments();
   if (isset($args[2])) {
     $show_mode = $args[2];
     return _rush_show($params, $show_mode, $rush_operations);
   }
   return drush_set_error('RUSH COMMAND ERROR', 'rush-show missing show argument.');
 }