Drush Rush: File System Helpers
File System Helpers
Helper Functions
Functions to get, set, and manage file and directory locations.
Functions
_rush_derive_make_file_path ($params, $make_file= 'default.make')
Return a make file location if it can be found.
rush_check_directories ()
Helper function to confirm important directories exists on the system.
rush_get_global_locations ()
Extract Rush application folder locations.
rush_list_files ($root= '.')
List the directories and files in the specified root directory.
Detailed Description
Functions to get, set, and manage file and directory locations.
Function Documentation
_rush_derive_make_file_path ($params, $make_file = 'default.make')
Return a make file location if it can be found.
Parameters
array $params An associative array of all rush parameters.
string $make_file A string containing the name of the make file. Defaults to: 'default.make'.
Returns
bool|string FALSE if no file is found. A string containing the path to the make file if found.
Definition at line 167 of file filesystem.inc.
Referenced by _rush_derive_parameters_build(), and rush_op_make().
{
   // Look for the make file in the build directory.
   // This first directory will not exist if it is a fresh build.  However, this
   // function will be called again when drush make is called, so a make file in
   // a build directory can be used.
   $make_file_path = $params['build']['directory_path'] . $make_file;
   if (file_exists($make_file_path)) {
     return $make_file_path;
   }
   // Look for the make file in the job directory.
   $make_file_path = $params['global_locations']['RUSH_JOB_DIRECTORY_PATH'] . $make_file;
   if (file_exists($make_file_path)) {
     return $make_file_path;
   }
   // Look for the make file in the top job directory.
   $make_file_path = $params['global_locations']['RUSH_JOB_TOP_DIRECTORY_PATH'] . $make_file;
   if (file_exists($make_file_path)) {
     return $make_file_path;
   }
   // Look for the make file in the Rush global directory.
   $make_file_path = $params['global_locations']['RUSH_ENVIRONMENT_DIRECTORY_PATH'] . $make_file;
   if (file_exists($make_file_path)) {
     return $make_file_path;
   }
   return FALSE;
 }
rush_check_directories ()
Helper function to confirm important directories exists on the system.
This function is currently not in use.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 26 of file filesystem.inc.
References rush_get_global_locations().
{
   $global_locations = rush_get_global_locations();
   if (!is_dir($global_locations['RUSH_HOME_DIRECTORY_PATH'])) {
     return drush_set_error('DRUSH_RUSH_NO_DIRECTORY', dt('[ERROR]: *** Cannot find the rush home directory !path ***', array('!path' => $global_locations['RUSH_HOME_DIRECTORY_PATH'])));
   }
   if (!is_dir($global_locations['RUSH_ENVIRONMENT_DIRECTORY_PATH'])) {
     return drush_set_error('DRUSH_RUSH_NO_DIRECTORY', dt('[ERROR]: *** Cannot find the rush global directory !path ***', array('!path' => $global_locations['RUSH_ENVIRONMENT_DIRECTORY_PATH'])));
   }
   if (!is_dir($global_locations['RUSH_JOBS_DIRECTORY_PATH'])) {
     return drush_set_error('DRUSH_RUSH_NO_DIRECTORY', dt('[ERROR]: *** Cannot find the rush jobs directory !path ***', array('!path' => $global_locations['RUSH_JOBS_DIRECTORY_PATH'])));
   }
   if (!is_dir($global_locations['RUSH_JOB_DIRECTORY_PATH'])) {
     return drush_set_error('DRUSH_RUSH_NO_DIRECTORY', dt('[ERROR]: *** Cannot find the rush job directory !path ***', array('!path' => $global_locations['RUSH_JOB_DIRECTORY_PATH'])));
   }
   return TRUE;
 }
rush_get_global_locations ()
Extract Rush application folder locations.
The following locations are derived in this function:
The Rush "application" folder.
The Rush folder should be in the user's home directory and should be named "Rush".
Uses drush_server_home() to find the home directory.
$global_locations['RUSH_HOME_DIRECTORY_PATH']
The global environment directory within the Rush application folder.
This is where global (system environment) params should be placed.
Using global params allows job folders to inherit system level information without the need to define the information more than once.
$global_locations['RUSH_ENVIRONMENT_DIRECTORY_PATH']
The jobs directory within the Rush application folder.
This is where single job folders may be placed.
$global_locations['RUSH_JOBS_DIRECTORY_PATH']
The specific job folder defined in the job argument at run time.
The params and rush files in here define build specific parameters and operations.
drush rush jobOne will run the params and operations included in the directory ~/Rush/jobs/jobOne/ .
$global_locations['RUSH_JOB_DIRECTORY_PATH']
See Also
rush_drush_command
drush_rush_rush
Returns
array An associative array with the path locations.
Definition at line 74 of file filesystem.inc.
References rush_self_path().
Referenced by drush_rush_list(), rush_check_directories(), rush_get_operations(), and rush_get_params().
{
   $global_locations['RUSH_HOME_DIRECTORY_NAME']          = 'Rush';
   $global_locations['RUSH_MODULE_DIRECTORY_PATH']        = rush_self_path();
   $global_locations['RUSH_ENVIRONMENT_DIRECTORY_NAME']   = 'environment';
   $global_locations['RUSH_JOBS_DIRECTORY_NAME']          = 'jobs';
   $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_NAME'] = 'RushTemplates';
   $global_locations['RUSH_SERVER_HOME']                  = drush_server_home() . '/';
   $global_locations['RUSH_HOME_DIRECTORY_PATH']          = $global_locations['RUSH_SERVER_HOME'] . $global_locations['RUSH_HOME_DIRECTORY_NAME'] . '/';
   $global_locations['RUSH_ENVIRONMENT_DIRECTORY_PATH']   = $global_locations['RUSH_HOME_DIRECTORY_PATH'] . $global_locations['RUSH_ENVIRONMENT_DIRECTORY_NAME'] . '/';
   $global_locations['RUSH_JOBS_DIRECTORY_PATH']          = $global_locations['RUSH_HOME_DIRECTORY_PATH'] . $global_locations['RUSH_JOBS_DIRECTORY_NAME'] . '/';
   $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_PATH'] = $global_locations['RUSH_MODULE_DIRECTORY_PATH'] . $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_NAME'] . '/';
   $args                                                  = drush_get_arguments();
   $job_arg                                               = $args[1];
   $job                                                   = str_replace('.', "/", $job_arg);
   $global_locations['RUSH_JOB_DIRECTORY_PATH']           = $global_locations['RUSH_JOBS_DIRECTORY_PATH'] . $job . '/';
   // Check whether the job directory exists.
   if (!is_dir($global_locations['RUSH_JOB_DIRECTORY_PATH'])) {
     // Don't set an error at this time.
     // drush_rush_validate() will handle error checking.
     // Instead switch to the job_templates directory.
     // This is mainly a convenience for Job Template developers to keep template
     // jobs separate from their own jobs and for people who want to update
     // template jobs with a simple replacement of the previous directory.
     $global_locations['RUSH_JOBS_DIRECTORY_PATH'] = $global_locations['RUSH_JOB_TEMPLATES_DIRECTORY_PATH'];
     $global_locations['RUSH_JOB_DIRECTORY_PATH']  = $global_locations['RUSH_JOBS_DIRECTORY_PATH'] . $job . '/';
   }
   // Check whether this is a sub job and if so, identify the top job directory.
   $job_directories = explode('.', $job_arg);
   if (count($job_directories) > 1) {
     $global_locations['RUSH_JOB_TOP_DIRECTORY_PATH'] = $global_locations['RUSH_JOBS_DIRECTORY_PATH'] . $job_directories[0] . '/';
   }
   return $global_locations;
 }
rush_list_files ($root = '.')
List the directories and files in the specified root directory.
Parameters
string $root Required. The root directory to begin listing within.
Returns
array An array of directories and files. $files['files'] is a list of all files. $files['dirs'] is a list of all directories.
Definition at line 121 of file filesystem.inc.
Referenced by drush_rush_list().
{
   $files       = array('files' => array(), 'dirs' => array());
   $directories = array();
   $last_letter = $root[strlen($root) - 1];
   $root        = ($last_letter == '\\' || $last_letter == '/') ? $root : $root . DIRECTORY_SEPARATOR;
   $directories[] = $root;
   while (count($directories)) {
     $dir = array_pop($directories);
     if ($handle = opendir($dir)) {
       while (FALSE !== ($file = readdir($handle))) {
         if ($file == '.' || $file == '..') {
           continue;
         }
         $file = $dir . $file;
         if (is_dir($file)) {
           $directory_path = $file . DIRECTORY_SEPARATOR;
           array_push($directories, $directory_path);
           $files['dirs'][] = $directory_path;
         }
         elseif (is_file($file)) {
           $files['files'][] = $file;
         }
       }
       closedir($handle);
     }
   }
   return $files;
 }