Drush Rush: Version Control Operations
Version Control Operations
Operations
Repo operation functions for Rush.
Functions
_rush_create_remote_repo_github ($params)
Create a remote repo using GITHUB's api.
rush_op_create_remote_repo ($params)
Create a remote repo using the given repo type.
rush_op_flow_init ($params)
Run git flow init -d in the specified directory.
rush_op_git_add ($params)
Run git add --all in the specified directory.
rush_op_git_branch ($params)
Run git branch to create a branch with the specified name.
rush_op_git_checkout ($params)
Run git checkout to checkout the specified branch, tag, or commit ID.
rush_op_git_clone ($params)
Run git clone into the specified directory.
rush_op_git_commit ($params)
Run git commit --all with a commit message.
rush_op_git_create_branch ($params)
Run git checkout -b to create and checkout a new branch with the specified name.
rush_op_git_init ($params)
Run git init in the specified directory.
rush_op_git_pull ($params)
Run git pull in the specified directory.
rush_op_git_push ($params)
Run git push in the specified directory.
rush_op_git_remote_add ($params)
Run git remote add in the specified directory.
Detailed Description
Repo operation functions for Rush.
Includes functions to:
Create remote github repos (public and private)
Initialize a git repo
Initialize a git flow ready repo
Run miscellaneous git commands
Function Documentation
_rush_create_remote_repo_github ($params)
Create a remote repo using GITHUB's api.
Parameters
array $params An associative array of all rush parameters.
$params['repo']['name'] string Required. The name of the remote repo to create.
$params['repo']['api_url'] string Required. A string containing the URL endpoint of the repo api such as, 'https://api.github.com'. With GitHub, the endpoint is 'https://api.github.com', unless working with an enterprise install. For an enterprise install use: yourdomain.com/api/v3/ See http://developer.github.com/v3/.
$params['repo']['api_account'] string Required. A string containing the URL argument to designate which account to use. With GitHub the string may be either:
'/user/' : This is the logged in user's individual account.
'/orgs/orgname' : In this case, orgname is an organization's account.
$params['repo']['user'] string Required. A string containing the API account user name. Typically a user's individual user account. $params['repo']['password'] string Required. A string containing the API account password. Typically a user's individual account password.
Returns
bool TRUE on success, FALSE on fail (via drush_set_error).
Definition at line 422 of file rush.repo.inc.
References rush_empty_error().
{
   if (empty($params['repo']['name'])) {
     return rush_empty_error('$params[\'repo\'][\'name\']', __FUNCTION__);
   }
   if (empty($params['repo']['api_url'])) {
     return rush_empty_error('$params[\'repo\'][\'api_url\']', __FUNCTION__);
   }
   if (empty($params['repo']['api_account'])) {
     return rush_empty_error('$params[\'repo\'][\'api_account\']', __FUNCTION__);
   }
   if (empty($params['repo']['user'])) {
     return rush_empty_error('$params[\'repo\'][\'user\']', __FUNCTION__);
   }
   if (empty($params['repo']['password'])) {
     return rush_empty_error('$params[\'repo\'][\'password\']', __FUNCTION__);
   }
   $data        = $params['repo'];
   $url         = $params['repo']['api_url'] . $params['repo']['api_account'] . '/repos';
   $u_p         = $params['repo']['user'] . ':' . $params['repo']['password'];
   $data_string = json_encode($data);
   $ch          = curl_init($url);
   curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
   $t_version = curl_version();
   curl_setopt($ch, CURLOPT_USERAGENT, 'curl/' . $t_version['version']);
   curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
   curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
   curl_setopt($ch, CURLOPT_USERPWD, $u_p);
   curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
   curl_setopt($ch, CURLOPT_HTTPHEADER, array(
     'Content-Type: application/json',
     'Content-Length: ' . strlen($data_string),
   ));
   $result       = curl_exec($ch);
   $final_result = json_decode($result, TRUE);
   if ($final_result['name'] != $data['name']) {
     $inspect_post = json_decode($data_string);
     drush_print_r($inspect_post);
     drush_print_r($final_result);
     return drush_set_error('RUSH_REPO_OP_ERROR', dt('[ERROR]: *** Unable to create a remote repo. ***'));
   }
   else {
     $msg = dt('[CREATE REMOTE REPO]: !htmlurl.', array('!htmlurl' => $final_result['html_url']));
     drush_log($msg, 'success');
     return TRUE;
   }
 }
rush_op_create_remote_repo ($params)
Create a remote repo using the given repo type.
This function is a factory which delegates action to other repo service functions. Though only one parameter is required for this function to route its parameters to the correct service function, the repo service functions get their parameters from those passed to this function.
Parameters
array $params An associative array of all rush parameters.
$params['repo']['service'] string Required. A string to designate the repo service such as 'github' or 'bitbucket'.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 46 of file rush.repo.inc.
References rush_empty_error().
{
   if (empty($params['repo']['service'])) {
     return rush_empty_error('$params[\'repo\'][\'service\']', __FUNCTION__);
   }
   $function = '_rush_create_remote_repo_' . $params['repo']['service'];
   if (function_exists($function)) {
     return $function($params);
   }
   else {
     return drush_set_error('RUSH_REPO_OP_ERROR', dt('[ERROR]: *** Unable to run !function ***', array('!function' => $function)));
   }
 }
rush_op_flow_init ($params)
Run git flow init -d in the specified directory.
Initialize a git flow ready repo in a specified directory. Note: Git flow must be installed and configured. See: https://github.com/nvie/gitflow
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 101 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   $cmd = 'cd ' . $params['build']['directory_path'] . ' ;git flow init -d';
   $msg = dt('[GIT FLOW INIT]: !path', array('!path' => $params['build']['directory_path']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_add ($params)
Run git add --all in the specified directory.
Add all files in the specified directory to git version control.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 125 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   $cmd = 'cd ' . $params['build']['directory_path'] . ' ; git add --all';
   $msg = dt('[GIT ADD ALL]: !path', array('!path' => $params['build']['directory_path']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_branch ($params)
Run git branch to create a branch with the specified name.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
$params['repo']['new_branch'] string Required. A string indicating the name of the new branch.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 218 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   if (empty($params['repo']['new_branch'])) {
     return rush_empty_error('$params[\'repo\'][\'new_branch\']', __FUNCTION__);
   }
   $msg = dt('[Branch]: !repo_new_branch ', array('!repo_new_branch' => $params['repo']['new_branch']));
   $cmd = 'cd ' . $params['build']['directory_path'] . '; git branch ' . $params['repo']['new_branch'];
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_checkout ($params)
Run git checkout to checkout the specified branch, tag, or commit ID.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
$params['repo']['checkout'] string Required. A string indicating which branch, tag, or commit to checkout.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 247 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   if (empty($params['repo']['checkout'])) {
     return rush_empty_error('$params[\'repo\'][\'checkout\']', __FUNCTION__);
   }
   $cmd = 'cd ' . $params['build']['directory_path'] . '; git checkout ' . $params['repo']['checkout'];
   $msg = dt('[CHECKOUT]: !branch ', array('!branch' => $params['repo']['checkout']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_clone ($params)
Run git clone into the specified directory.
Clone a repo to the specified directory.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
$params['repo']['url'] string Required. A string containing the URL of the repo.
$params['repo']['branch'] string Required. A string indicating which branch to push to. Defaults to 'master'.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 340 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   if (empty($params['repo']['url'])) {
     return rush_empty_error('$params[\'repo\'][\'url\']', __FUNCTION__);
   }
   if (empty($params['repo']['branch'])) {
     return rush_empty_error('$params[\'repo\'][\'branch\']', __FUNCTION__);
   }
   $note = dt('[START GIT CLONE]: Starting: git clone !repo_url !directory_path --branch=!branch .  This may take some time.***', array(
     '!repo_url'       => $params['repo']['url'],
     '!directory_path' => $params['build']['directory_path'],
     '!branch'         => $params['repo']['branch'],
   ));
   drush_log($note, 'status');
   $cmd = 'git clone ' . $params['repo']['url'] . ' ' . $params['build']['directory_path'] . ' --branch=' . $params['repo']['branch'];
   $msg = dt('[GIT CLONE]: git clone !repo_url !directory_path --branch=!branch ***', array(
     '!repo_url'       => $params['repo']['url'],
     '!directory_path' => $params['build']['directory_path'],
     '!branch'         => $params['repo']['branch'],
   ));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_commit ($params)
Run git commit --all with a commit message.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
$params['repo']['commit_message'] string Required. A string containing a commit message. Defaults to: 'Auto Commit by Drush Rush'
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 152 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   if (empty($params['repo']['commit_message'])) {
     return rush_empty_error('$params[\'repo\'][\'commit_message\']', __FUNCTION__);
   }
   $build_directory_path = $params['build']['directory_path'];
   $repo_commit_message  = $params['repo']['commit_message'];
   $cmd                  = "cd $build_directory_path; git commit --all -m '$repo_commit_message'";
   $msg                  = dt('[GIT COMMIT ALL]: !path', array('!path' => $params['build']['directory_path']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_create_branch ($params)
Run git checkout -b to create and checkout a new branch with the specified name.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
$params['repo']['create_branch'] string Required. A string indicating the name of the new branch.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 276 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   if (empty($params['repo']['create_branch'])) {
     return rush_empty_error('$params[\'repo\'][\'create_branch\']', __FUNCTION__);
   }
   $msg = dt('[Create Branch]: !repo_new_branch ', array('!repo_new_branch' => $params['repo']['create_branch']));
   $cmd = 'cd ' . $params['build']['directory_path'] . '; git checkout -b ' . $params['repo']['create_branch'];
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_init ($params)
Run git init in the specified directory.
Initialize a git repo in a specified directory.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 74 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   $cmd = 'git init ' . $params['build']['directory_path'];
   $msg = dt('[GIT INIT]: !path', array('!path' => $params['build']['directory_path']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_pull ($params)
Run git pull in the specified directory.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 380 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   $cmd = 'cd ' . $params['build']['directory_path'] . '; git pull';
   $msg = dt('[GIT PULL]: to !path', array('!path' => $params['build']['directory_path']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_push ($params)
Run git push in the specified directory.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
$params['repo']['remote'] string Required. A string indicating which remote to push to. Defaults to 'origin'.
$params['repo']['branch'] string Required. A string indicating which branch to push to. Defaults to 'master'.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 186 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   if (empty($params['repo']['remote'])) {
     return rush_empty_error('$params[\'repo\'][\'remote\']', __FUNCTION__);
   }
   if (empty($params['repo']['branch'])) {
     return rush_empty_error('$params[\'repo\'][\'branch\']', __FUNCTION__);
   }
   $cmd = 'cd ' . $params['build']['directory_path'] . '; git push ' . $params['repo']['remote'] . ' ' . $params['repo']['branch'];
   $msg = dt('[PUSH TO REPO]: Code pushed to repo from !path', array('!path' => $params['build']['directory_path']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }
rush_op_git_remote_add ($params)
Run git remote add in the specified directory.
Parameters
array $params An associative array of all rush parameters.
$params['build']['directory_path'] string Required. A string containing the path to the build's directory.
$params['repo']['url'] string Required. A string containing the URL of the repo.
Returns
bool Returns TRUE on success or FALSE on fail (via drush_set_error).
Definition at line 306 of file rush.repo.inc.
References rush_empty_error(), and rush_shell_exec().
{
   if (empty($params['build']['directory_path'])) {
     return rush_empty_error('$params[\'build\'][\'directory_path\']', __FUNCTION__);
   }
   if (empty($params['repo']['url'])) {
     return rush_empty_error('$params[\'repo\'][\'url\']', __FUNCTION__);
   }
   $cmd = 'cd ' . $params['build']['directory_path'] . '; git remote add --track master origin ' . $params['repo']['url'];
   $msg = dt('[GIT REMOTE ADD]: !path', array('!path' => $params['build']['directory_path']));
   return rush_shell_exec($cmd, $msg, 'RUSH_REPO_OP_ERROR', __FUNCTION__);
 }