Drush Rush: Rush Command Executions
Rush Command Executions
Bootstrap
Functions used by the drush rush command to execute operations.
Functions
rush_command_exec ($command, $params=array())
Run a command through drush_shell_exec().
rush_function_exec ($function, $params)
Execute the defined rush function.
rush_job_exec ($job)
Run another Rush Job via drush_shell_exec().
rush_message_exec ($message)
Print a rush message through drush_log().
Detailed Description
Functions used by the drush rush command to execute operations.
Function Documentation
rush_command_exec ($command, $params = array())
Run a command through drush_shell_exec().
Parameters
string $command Required. A string with the command to run through drush_shell_exec.
array $params (Optional) An associative array of all rush parameters. Not used yet.
Returns
bool TRUE on success. FALSE on fail via drush_set_error.
Backlog:
Look for a better way to add url to drush functions. It may not always be accurate this way.
Would like an away to abort if an operation failed.
Definition at line 383 of file rush.drush.inc.
Referenced by drush_rush(), and rush_op_open_uri().
{
   // If this is a drush command then run it in the docroot directory.
   $pos = strpos($command, 'drush');
   // Using != would not work as expected
   // because a position can be 0. The statement (0 != false) evaluates
   // to false.
   if ($pos !== FALSE) {
     $command = 'cd ' . $params['build']['docroot_path'] . '; ' . $command . ' --uri=' . $params['build']['site_uri'];
   }
   // If it's not a drush command, then run it in the build directory.
   else {
     $command = 'cd ' . $params['build']['directory_path'] . '; ' . $command;
   }
   if (drush_shell_exec($command)) {
     $msg = dt('[RUSH COMMAND EXEC]: !command', array('!command' => $command));
     drush_log($msg, 'success');
     return TRUE;
   }
   else {
     $msg = dt('!command', array('!command' => $command));
     return drush_set_error('RUSH_COMMAND_EXEC_FAILED', $msg);
   }
 }
rush_function_exec ($function, $params)
Execute the defined rush function.
Parameters
string $function Required. A string with the rush function to run.
array $params Required. An associative array of all rush parameters.
Returns
bool TRUE on success, FALSE on fail via drush_set_error.
Backlog:
Check the return of the function for errors.
Definition at line 472 of file rush.drush.inc.
Referenced by drush_rush().
{
   $operation = 'rush_op_' . $function;
   if (function_exists($operation)) {
     $msg = dt('[RUSH OPERATION CALL]: !function', array('!function' => $function));
     drush_log($msg, 'success');
     return $operation($params);
   }
   else {
     $msg = dt('!function does not exist or has not been included.', array('!function' => $operation));
     return drush_set_error('RUSH_FUNCTION_EXEC_FAILED', $msg);
   }
 }
rush_job_exec ($job)
Run another Rush Job via drush_shell_exec().
Parameters
string $job Required. A string with the job to run through drush_shell_exec.
Returns
bool TRUE on success. FALSE on fail via drush_set_error.
Definition at line 420 of file rush.drush.inc.
Referenced by drush_rush().
{
   $command = 'drush rush ' . $job;
   if (drush_shell_exec($command)) {
     $results = drush_shell_exec_output();
     foreach ($results as $result) {
       drush_print($result);
     }
     $msg = dt('[RUSH JOB EXEC]: !command', array('!command' => $command));
     drush_log($msg, 'success');
     return TRUE;
   }
   else {
     $msg = dt('!command', array('!command' => $command));
     return drush_set_error('RUSH_JOB_EXEC_FAILED', $msg);
   }
 }
rush_message_exec ($message)
Print a rush message through drush_log().
Parameters
string $message Required. A string with the message to print through drush_log().
Returns
bool TRUE.
Note
No real error checking needed right now.
Definition at line 452 of file rush.drush.inc.
Referenced by drush_rush().
{
   $msg = dt('[RUSH MESSAGE]: !message', array('!message' => $message));
   drush_log($msg, 'status');
   return TRUE;
 }