Drush Rush: Output Helpers
Output Helpers
Helper Functions
Functions to assist with text output.
Functions
_rush_format_docblocks ($docblocks)
Get an array of formatted block comments from the $docblocks array.
_rush_get_function_names ($file)
Given a file path, return an array of function names in the file.
_rush_print_ops_table ($file)
Print a table of operation functions.
_rush_print_ops_tables ($ops)
Helper function to print tables for each group of operations.
rush_empty_error ($value, $function)
Helper function to output a consistent error message for empty parameters.
rush_get_docblocks ($functions)
Get an array of doc block comments from an array of function names.
rush_message_wrapper ($message= '', $style=0)
Style messages for output to the console.
rush_print_function_blocks ($file)
Print the docblocks for functions in the specified file.
Detailed Description
Functions to assist with text output.
Function Documentation
_rush_format_docblocks ($docblocks)
Get an array of formatted block comments from the $docblocks array.
This is a helper function to format doc block comments for output.
Parameters
array $docblocks An array of function names as the key and docblocks as the value.
Returns
array An array of function names as the key and docblocks as the value.
Definition at line 100 of file output.inc.
Referenced by _rush_print_ops_table(), and rush_print_function_blocks().
{
   $functions = array();
   foreach ($docblocks as $f_name => $f_doc_block) {
     $strip = array("*", "/");
     $f_doc_block = str_replace($strip, "", $f_doc_block);
     $f_doc_block = str_replace('@param', "Parameter:", $f_doc_block);
     $f_doc_block = str_replace('@return', "Returns:", $f_doc_block);
     $functions[$f_name] = $f_doc_block;
   }
   return $functions;
 }
_rush_get_function_names ($file)
Given a file path, return an array of function names in the file.
Parameters
string $file String containing the path to the file.
Returns
array An array of function names found in the file.
Definition at line 123 of file output.inc.
Referenced by _rush_print_ops_table(), and rush_print_function_blocks().
{
   $content = file_get_contents($file);
   $functions_names = array();
   preg_match_all("/(function )(\S*\(\S*\))/", $content, $matches);
   foreach ($matches[2] as $match) {
     // @todo Get the right regex.
     $match = trim($match);
     $match = str_replace('($params)', '', $match);
     $functions_names[] = $match;
   }
   natcasesort($functions_names);
   return $functions_names;
 }
_rush_print_ops_table ($file)
Print a table of operation functions.
Parameters
string $file The name of the file to get the docblocks from for printing.
Definition at line 164 of file output.inc.
References _rush_format_docblocks(), _rush_get_function_names(), rush_get_docblocks(), and rush_self_path().
Referenced by _rush_print_ops_tables().
{
   $docs_dir = rush_self_path() . 'operations/';
   $function_names = _rush_get_function_names($docs_dir . $file);
   $docblocks = rush_get_docblocks($function_names);
   $docblocks = _rush_format_docblocks($docblocks);
   $rows = array();
   foreach ($docblocks as $f_name => $doc) {
     $f_name = str_replace('rush_op_', '', $f_name);
     $doc = strtok($doc, "\n");
     $rows[$f_name] = $doc;
   }
   $rows = drush_key_value_to_array_table($rows);
   drush_print_table($rows);
 }
_rush_print_ops_tables ($ops)
Helper function to print tables for each group of operations.
Parameters
array $ops An array of operation group file name roots. 'rush.' . [root] . '.inc';
Definition at line 185 of file output.inc.
References _rush_print_ops_table().
{
   $ops = drush_map_assoc($ops);
   foreach ($ops as $op) {
     $file = 'rush.' . $op . '.inc';
     _rush_print_ops_table($file);
   }
 }
rush_empty_error ($value, $function)
Helper function to output a consistent error message for empty parameters.
Parameters
string $value Required. A string containing the name of the parameter missing a value.
string $function Required. A string containing the name of the calling function.
Returns
bool Always returns FALSE via drush_set_error()
Definition at line 29 of file output.inc.
Referenced by _rush_create_remote_repo_github(), _rush_dns_exists(), _rush_get_si_options(), _rush_settings_local_params(), rush_op_create_build_directory(), rush_op_create_directories(), rush_op_create_files(), rush_op_create_git_ignore(), rush_op_create_remote_repo(), rush_op_create_vhost(), rush_op_delete_vhost(), rush_op_destroy_build_directory(), rush_op_flow_init(), rush_op_git_add(), rush_op_git_branch(), rush_op_git_checkout(), rush_op_git_clone(), rush_op_git_commit(), rush_op_git_create_branch(), rush_op_git_init(), rush_op_git_pull(), rush_op_git_push(), rush_op_git_remote_add(), rush_op_make(), rush_op_open_uri(), rush_op_set_drupal_variables(), rush_op_si(), rush_op_sql_create(), rush_op_sql_destroy_db(), rush_op_sql_dump(), rush_op_sql_query(), and rush_op_sql_query_file().
{
   return drush_set_error('RUSH_EMPTY_VALUE', dt('[ERROR]: *** !value should be set when calling !function. ***', array(
     '!value'    => $value,
     '!function' => $function,
   )));
 }
rush_get_docblocks ($functions)
Get an array of doc block comments from an array of function names.
Uses PHP ReflectionFunction Class for doc comment reflection. The function names passed to this function must be functions which are defined in the current runtime.
Parameters
array $functions An array of function names.
Returns
array An array of function names as the key and docblocks as the value.
Definition at line 75 of file output.inc.
Referenced by _rush_print_ops_table(), and rush_print_function_blocks().
{
   $docblocks = array();
   foreach ($functions as $func) {
     $f = new ReflectionFunction($func);
     $f_name = $f->getName();
     $f_doc_block = $f->getDocComment();
     $docblocks[$f_name] = $f_doc_block;
   }
   return $docblocks;
 }
rush_message_wrapper ($message = '', $style = 0)
Style messages for output to the console.
Parameters
string $message A string containing the message text to style.
int $style An integer indicating which style to use for the message.
Returns
string The styled message string.
Definition at line 48 of file output.inc.
Referenced by _rush_show(), and drush_rush_list().
{
   $msg = '';
   switch ($style) {
     case 0:
       $msg .= "\n**********$message********************************************\n";
       break;
   }
   $msg = substr($msg, 0, 80);
   return ($msg);
 }
rush_print_function_blocks ($file)
Print the docblocks for functions in the specified file.
Parameters
string $file A string containing the name of the file to parse for docblocks.
Definition at line 145 of file output.inc.
References _rush_format_docblocks(), _rush_get_function_names(), and rush_get_docblocks().
{
   $function_names = _rush_get_function_names($file);
   $docblocks = rush_get_docblocks($function_names);
   $docblocks = _rush_format_docblocks($docblocks);
   foreach ($docblocks as $f_name => $doc) {
     $msg = '*** ' . $f_name . ' ***';
     drush_print($msg);
     drush_print($doc);
   }
 }